### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by foysalremon** [chflame163/ComfyUI_CatVTON_Wrapper#24]
I think it's because you don't add support for other gpu like intel arc which doesn't have cuda. If so, requesting to add support
## Error Details
- **Node Type:** CatVTONWrapper
- **Exception Type:** AssertionError
- **Exception Message:** Torch not compiled with CUDA enabled
## Stack Trace
```
  File "G:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "G:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "G:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "G:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "G:\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\cat_vton.py", line 42, in catvton
    pipeline = CatVTONPipeline(

  File "G:\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\catvton\pipeline.py", line 42, in __init__
    self.vae = AutoencoderKL.from_pretrained(os.path.join(folder_paths.models_dir, "CatVTON", "sd-vae-ft-mse")).to(device, dtype=weight_dtype)

  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)

  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)

  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)

  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)

  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")

```
## System Information
- **ComfyUI Version:** v0.2.2-58-g38c6908
- **Arguments:** main.py --bf16-unet
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.0a0+cxx11.abi
## Devices

- **Name:** xpu
  - **Type:** xpu
  - **VRAM Total:** 8319483904
  - **VRAM Free:** 4993683456
  - **Torch VRAM Total:** 3487563776
  - **Torch VRAM Free:** 161763328

## Logs
```
2024-09-22 16:26:39,791 - root - INFO - Total VRAM 7934 MB, total RAM 32556 MB
2024-09-22 16:26:39,791 - root - INFO - pytorch version: 2.1.0a0+cxx11.abi
2024-09-22 16:26:39,792 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-22 16:26:39,792 - root - INFO - Device: xpu
2024-09-22 16:26:39,809 - root - INFO - Using pytorch cross attention
2024-09-22 16:26:40,395 - root - INFO - [Prompt Server] web root: G:\ComfyUI\web
2024-09-22 16:26:43,101 - root - INFO - 
Import times for custom nodes:
2024-09-22 16:26:43,101 - root - INFO -    0.0 seconds: G:\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-22 16:26:43,101 - root - INFO -    0.0 seconds: G:\ComfyUI\custom_nodes\ComfyUI_pose_inter
2024-09-22 16:26:43,101 - root - INFO -    0.0 seconds: G:\ComfyUI\custom_nodes\cg-use-everywhere
2024-09-22 16:26:43,101 - root - INFO -    0.0 seconds: G:\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-09-22 16:26:43,101 - root - INFO -    0.0 seconds: G:\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper
2024-09-22 16:26:43,101 - root - INFO -    0.1 seconds: G:\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-09-22 16:26:43,101 - root - INFO -    0.2 seconds: G:\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-09-22 16:26:43,101 - root - INFO -    0.2 seconds: G:\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-22 16:26:43,101 - root - INFO -    0.3 seconds: G:\ComfyUI\custom_nodes\ComfyUI-Dwpose-Tensorrt
2024-09-22 16:26:43,102 - root - INFO -    0.4 seconds: G:\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-09-22 16:26:43,102 - root - INFO -    0.8 seconds: G:\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-09-22 16:26:43,102 - root - INFO - 
2024-09-22 16:26:43,109 - root - INFO - Starting server

2024-09-22 16:26:43,109 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-22 16:26:46,973 - root - INFO - got prompt
2024-09-22 16:26:47,032 - comfyui_segment_anything - WARNING - using extra model: G:\ComfyUI\models\sams\sam_vit_h_4b8939.pth
2024-09-22 16:27:02,235 - root - ERROR - !!! Exception during processing !!! Torch not compiled with CUDA enabled
2024-09-22 16:27:02,236 - root - ERROR - Traceback (most recent call last):
  File "G:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "G:\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\cat_vton.py", line 42, in catvton
    pipeline = CatVTONPipeline(
  File "G:\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\catvton\pipeline.py", line 42, in __init__
    self.vae = AutoencoderKL.from_pretrained(os.path.join(folder_paths.models_dir, "CatVTON", "sd-vae-ft-mse")).to(device, dtype=weight_dtype)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

2024-09-22 16:27:02,237 - root - INFO - Prompt executed in 15.26 seconds
2024-09-22 16:27:12,577 - root - INFO - got prompt
2024-09-22 16:27:12,626 - root - ERROR - !!! Exception during processing !!! Torch not compiled with CUDA enabled
2024-09-22 16:27:12,626 - root - ERROR - Traceback (most recent call last):
  File "G:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "G:\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\cat_vton.py", line 42, in catvton
    pipeline = CatVTONPipeline(
  File "G:\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\catvton\pipeline.py", line 42, in __init__
    self.vae = AutoencoderKL.from_pretrained(os.path.join(folder_paths.models_dir, "CatVTON", "sd-vae-ft-mse")).to(device, dtype=weight_dtype)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "G:\ComfyUI\comfyui_env\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

2024-09-22 16:27:12,627 - root - INFO - Prompt executed in 0.05 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":6,"last_link_id":6,"nodes":[{"id":3,"type":"LayerMask: SegmentAnythingUltra V2","pos":{"0":414,"1":424},"size":{"0":428.4000244140625,"1":342},"flags":{},"order":2,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":1}],"outputs":[{"name":"image","type":"IMAGE","links":null,"shape":3},{"name":"mask","type":"MASK","links":[2,3],"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"LayerMask: SegmentAnythingUltra V2"},"widgets_values":["sam_vit_h (2.56GB)","GroundingDINO_SwinT_OGC (694MB)",0.3,"VITMatte",6,6,0.01,0.99,false,"shirt, pants,","cuda",2],"color":"rgba(27, 80, 119, 0.7)"},{"id":4,"type":"LayerMask: MaskPreview","pos":{"0":903,"1":444},"size":{"0":277.20001220703125,"1":246},"flags":{},"order":3,"mode":0,"inputs":[{"name":"mask","type":"MASK","link":2}],"outputs":[],"properties":{"Node name for S&R":"LayerMask: MaskPreview"},"color":"rgba(27, 80, 119, 0.7)"},{"id":5,"type":"CatVTONWrapper","pos":{"0":901,"1":32},"size":{"0":315,"1":218},"flags":{},"order":4,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":5},{"name":"mask","type":"MASK","link":3},{"name":"refer_image","type":"IMAGE","link":4}],"outputs":[{"name":"image","type":"IMAGE","links":[6],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CatVTONWrapper"},"widgets_values":[25,"fp16",549557970686997,"randomize",40,2.5]},{"id":6,"type":"PreviewImage","pos":{"0":1273,"1":33},"size":{"0":323.8887023925781,"1":455.15203857421875},"flags":{},"order":5,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":6}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"}},{"id":1,"type":"LoadImage","pos":{"0":45,"1":28},"size":{"0":309.2167053222656,"1":333.2966613769531},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[1,5],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["13735824_1108784102510186_1530724342781074013_o.jpg","image"]},{"id":2,"type":"LoadImage","pos":{"0":45,"1":423},"size":{"0":308.3948059082031,"1":348.0320739746094},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[4],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["71AihluQr1L._AC_SX569__upscayl_4x_ultrasharp.jpg","image"]}],"links":[[1,1,0,3,0,"IMAGE"],[2,3,1,4,0,"MASK"],[3,3,1,5,1,"MASK"],[4,2,0,5,2,"IMAGE"],[5,1,0,5,0,"IMAGE"],[6,5,0,6,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.9090909090909095,"offset":[291.0420536792561,101.14600019424024]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by chflame163** [comment]
I did not have corresponding device testing, so in order to prevent problems, I removed the code for these devices.

**Comment by foysalremon** [comment]
@chflame163 Could this be added? I have an Intel Arc 750 available for testing. Alternatively, could it be provided in a separate branch for those who need it? Non-CUDA GPUs are becoming more popular these days, so it would be great to support them.

**Comment by zixuan96** [comment]
> I did not have corresponding device testing, so in order to prevent problems, I removed the code for these devices.

I'm using Apple M2 and M3 chip. I will be very grateful if you could add them back, so that other guys and I can use this extension and then provide feedback on Non-CUDA GPUs.

**Comment by chflame163** [comment]
I tried to run it on intel CPU，but was unsuccessful,  so I don't plan to continue. Sorry guys.

**Comment by malinowskij** [comment]
Just edit: cat_vton.py from 'cuda' to 'mps: 
<img width="789" alt="image" src="https://github.com/user-attachments/assets/3335657e-35c4-4bc9-af10-69033b8ec1a1" />

But now I have other error :D : 
<img width="360" alt="image" src="https://github.com/user-attachments/assets/981f9606-f804-4964-80cb-db6fe3d478f4" />

**Comment by zer0factor** [comment]
> Just edit: cat_vton.py from 'cuda' to 'mps: <img alt="image" width="789" src="https://private-user-images.githubusercontent.com/20030679/396475036-3335657e-35c4-4bc9-af10-69033b8ec1a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDU3MTQsIm5iZiI6MTczNDgwNTQxNCwicGF0aCI6Ii8yMDAzMDY3OS8zOTY0NzUwMzYtMzMzNTY1N2UtMzVjNC00YmM5LWFmMTAtNjkwMzNiOGVjMWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE4MjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYjZjNGMyZGYwYzg1ZmE5ZTAwNDdlZjhkMDBmM2M2NzhmNTcyNGQ4MWU3Y2EyYjE0ZTQyM2ZkMzQwYTBjZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FDj1X8deK9KpCOv0ONvCcLAc7EqpCzxoj6EIqaPHvBY">
> 
> But now I have other error :D : <img alt="image" width="360" src="https://private-user-images.githubusercontent.com/20030679/396475186-981f9606-f804-4964-80cb-db6fe3d478f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDU3MTQsIm5iZiI6MTczNDgwNTQxNCwicGF0aCI6Ii8yMDAzMDY3OS8zOTY0NzUxODYtOTgxZjk2MDYtZjgwNC00OTY0LTgwY2ItZGI2ZmUzZDQ3OGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE4MjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YWRiOGNlMGUxOWViOWFmMzNiNWU1NThjYWYwMzc3YmI1NjI5OTg5YTZlMjI4MWVkOWMzNDFiZDM4NmFjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.muznEd0IE30o4A34V3NyhVfJyTIm52kEVqK0z_wOw4I">
> 
> Ok, no longer valid problem. I modified code that now use windowed attention and it works. <img alt="image" width="798" src="https://private-user-images.githubusercontent.com/20030679/396484816-dcae8152-c40c-4094-af7b-2506f55c994c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDU3MTQsIm5iZiI6MTczNDgwNTQxNCwicGF0aCI6Ii8yMDAzMDY3OS8zOTY0ODQ4MTYtZGNhZTgxNTItYzQwYy00MDk0LWFmN2ItMjUwNmY1NWM5OTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE4MjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZTE1NzY3NGUzY2MyNDJiOTI3ZGM5MWIxOGYzZGZhMTI5OWFkZjhjMTRiZDc0OGE4Yjg3YzQ1YzI0NjIyNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CFoseVbqDT3pmr6o8OpqqbPCEaKs_-Fub_mvVT1wuJY">
> 
> But... not as expected :D From this: <img alt="image" width="261" src="https://private-user-images.githubusercontent.com/20030679/396485187-f70618ad-5818-4e35-bc4c-e794fbeadca8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDU3MTQsIm5iZiI6MTczNDgwNTQxNCwicGF0aCI6Ii8yMDAzMDY3OS8zOTY0ODUxODctZjcwNjE4YWQtNTgxOC00ZTM1LWJjNGMtZTc5NGZiZWFkY2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE4MjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OTZiMjljOGU4YzljNzNhYmVlZTAyYzJhZmIzNjM1MjdkYzRmODE0NTY3MWIwODc1Y2QyZDk4OTU5YWE0MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eE-kjpJkBiFZz1HfCCtKcNCwK_np6Q6PFOsb7g6qONY">
> 
> To: <img alt="image" width="261" src="https://private-user-images.githubusercontent.com/20030679/396485261-7981aa24-f466-4e50-ba02-d03c2b20a31a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDU3MTQsIm5iZiI6MTczNDgwNTQxNCwicGF0aCI6Ii8yMDAzMDY3OS8zOTY0ODUyNjEtNzk4MWFhMjQtZjQ2Ni00ZTUwLWJhMDItZDAzYzJiMjBhMzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE4MjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYTcwMTYzOTM1OTFiYjkyM2ExNDY2NmY2NDYwOTBiZjRlYjVmMTdhZTFkNTg5ZmU4ODE4NmYwMDhhZGM2YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D7CbTydHSA3Gokf_2bGgNbBJwtcIU-8YJGV1pr9aAHA">
> 
> Time for buying RTX with CUDA support, not apple silicon 😛

hi, what windowed attention code did you use? Thanks, i need to try it myself to know i really need an rtx.

**Comment by eljabbaryhicham** [comment]
i tried your solution but the node won't load!!

**Comment by JC-lurker** [comment]
> i tried your solution but the node won't load!!

You need to install whatever is missing. Which we wouldn’t know what from just one sentence.

**Comment by sahaib** [comment]
@zer0factor What memory management did you exactly did in attn_processor.py? I'm running on MBP M4 Pro 24 GB Ram..

**Comment by izzo83** [comment]
@JC-lurker 

> like [@malinowskij](https://github.com/malinowskij) . Solved with these step. ![Screenshot 2024-12-22 at 3 40 42 PM](https://github.com/user-attachments/assets/14202afa-b10b-466e-8d83-b316d2e269db)
> 
> ComfyUI_CatVTON_Wrapper cat_vton.py `device = "mps"`
> 
> segment_anything build_sam_hq.py `state_dict = torch.load(f, map_location=torch.device("mps"))`
> 
> ComfyUI_CatVTON_Wrapper attn_processor.py Did some memory managment here.

Can you please help describe with the memory management that you did? I've tried to ask chatgpt but unsuccesful

**Comment by JC-lurker** [comment]
Basically have to rewrite code for the attn memory into smaller chunks. Just ask ChatGPT to do it for you.

i think the code has already changed and i forgot which version this is, but here the code
ComfyUI_CatVTON_Wrapper attn_processor.py

`from torch.nn import functional as F
import torch
class SkipAttnProcessor(torch.nn.Module):
def __init__(self, *args, **kwargs) -> None:
super().__init__()
def __call__(
self,
attn,
hidden_states,
encoder_hidden_states=None,
attention_mask=None,
temb=None,
):
return hidden_states
class AttnProcessor2_0(torch.nn.Module):
"""
Processor for implementing scaled dot-product attention with memory optimizations.
Requires PyTorch 2.0+.
"""
def __init__(self, hidden_size=None, cross_attention_dim=None, **kwargs):
super().__init__()
if not hasattr(F, "scaled_dot_product_attention"):
raise ImportError("AttnProcessor2_0 requires PyTorch 2.0+. Upgrade PyTorch to 2.0 or later.")
self.hidden_size = hidden_size
self.cross_attention_dim = cross_attention_dim
def forward_chunked_attention(self, query, key, value, attention_mask, chunk_size):
"""
Process attention in chunks to reduce memory usage.
"""
num_heads, seq_len, head_dim = query.shape[1], query.shape[2], query.shape[3]
output = []
for i in range(0, seq_len, chunk_size):
query_chunk = query[:, :, i:i + chunk_size, :]
if attention_mask is not None:
attn_mask_chunk = attention_mask[:, :, :, i:i + chunk_size]
else:
attn_mask_chunk = None
attention_chunk = F.scaled_dot_product_attention(
query_chunk, key, value, attn_mask=attn_mask_chunk, dropout_p=0.0, is_causal=False
)
output.append(attention_chunk)
return torch.cat(output, dim=2)
def __call__(
self,
attn,
hidden_states,
encoder_hidden_states=None,
attention_mask=None,
temb=None,
chunk_size=64,
use_mixed_precision=True,
):
residual = hidden_states
# Apply spatial norm if available
if attn.spatial_norm is not None:
hidden_states = attn.spatial_norm(hidden_states, temb)
input_ndim = hidden_states.ndim
if input_ndim == 4:
batch_size, channel, height, width = hidden_states.shape
hidden_states = hidden_states.view(batch_size, channel, height * width).transpose(1, 2)
batch_size, sequence_length, _ = (
hidden_states.shape if encoder_hidden_states is None else encoder_hidden_states.shape
)
if attention_mask is not None:
attention_mask = attn.prepare_attention_mask(attention_mask, sequence_length, batch_size)
attention_mask = attention_mask.view(batch_size, attn.heads, -1, attention_mask.shape[-1])
if attn.group_norm is not None:
hidden_states = attn.group_norm(hidden_states.transpose(1, 2)).transpose(1, 2)
# Compute Q, K, V
query = attn.to_q(hidden_states)
if encoder_hidden_states is None:
encoder_hidden_states = hidden_states
elif attn.norm_cross:
encoder_hidden_states = attn.norm_encoder_hidden_states(encoder_hidden_states)
key = attn.to_k(encoder_hidden_states)
value = attn.to_v(encoder_hidden_states)
inner_dim = key.shape[-1]
head_dim = inner_dim // attn.heads
query = query.view(batch_size, -1, attn.heads, head_dim).transpose(1, 2)
key = key.view(batch_size, -1, attn.heads, head_dim).transpose(1, 2)
value = value.view(batch_size, -1, attn.heads, head_dim).transpose(1, 2)
if use_mixed_precision:
query = query.to(torch.float16)
key = key.to(torch.float16)
value = value.to(torch.float16)
# Use chunked attention
hidden_states = self.forward_chunked_attention(query, key, value, attention_mask, chunk_size)
hidden_states = hidden_states.transpose(1, 2).reshape(batch_size, -1, attn.heads * head_dim)
hidden_states = hidden_states.to(query.dtype)
# Linear projection
hidden_states = attn.to_out[0](hidden_states)
hidden_states = attn.to_out[1](hidden_states) # Apply dropout if defined
if input_ndim == 4:
hidden_states = hidden_states.transpose(-1, -2).reshape(batch_size, channel, height, width)
if attn.residual_connection:
hidden_states = hidden_states + residual
hidden_states = hidden_states / attn.rescale_output_factor
return hidden_states
`
